name = "allorigins"
type = "webpack"
account_id = "your_account_id"
workers_dev = true
compatibility_date = "2023-05-18"

[build]
command = "yarn install"
[build.upload]
format = "service-worker"
main = "./server.js"
